source "http://rubygems.org"

# Sinatra
gem "sinatra"
gem "sinatra-contrib"

# Data mapper
gem "data_mapper"
gem "dm-sqlite-adapter"
gem "dm-serializer"

# Server (Thin)
gem "thin"

# Frontend
gem "slim"